runtime: nodejs20
env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
entrypoint: npm start
env_variables:
  DATABASE_URL: "postgresql://master_ed_user:Mss2912!@35.203.49.196:5432/master_ed_users?schema=public"
  NEXTAUTH_SECRET: ${sm://nextauth-secret}
  NEXTAUTH_URL: "https://ultimate-life-438505-t2.nn.r.appspot.com"